name: Deploy All Images

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: numerai_predict

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  public-image:
    strategy:
      matrix:
        python-version: ['3{0}10', '3{0}11', '3{0}12']
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Extract short git SHA
        run: echo "GIT_REF=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: Log in to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}_py_${{ format(matrix.python-version, '_') }}

      - name: Push Docker image as LATEST to Github Container registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./py${{ format(matrix.python-version, '.') }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}_py_${{ format(matrix.python-version, '_') }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push Docker image git ref to Github Container registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./py${{ format(matrix.python-version, '.') }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}_py_${{ format(matrix.python-version, '_') }}:${{ env.GIT_REF }}
          labels: ${{ steps.meta.outputs.labels }}

  internal-py312-image:
    strategy:
      matrix:
        python-version: ['3{0}10', '3{0}11', '3{0}12']
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MODEL_UPLOADS_ACCOUNT_ID }}:role/github-actions
          aws-region: us-west-2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        run: ACCOUNT_ID=${{ secrets.MODEL_UPLOADS_ACCOUNT_ID }} make push_latest_${{ format(matrix.python-version, '_') }}
